[project]
name = "nullmodels"
version = "0.1.0"
description = "Nullmodel precision-recall curve simulations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.1",
    "scipy>=1.15.1",
    "pandas>=2.2.3",
    "plotnine>=0.14.4",
]

[dependency-groups]
dev = [
    "marimo>=0.16.5",
    "ruff>=0.14.0",
]

[project.urls]
source = "https://github.com/mart-mihkel/nullmodels"

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["nullmodels"]
exclude = ["notebooks"]
